name: Arduino Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Arduino Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 'latest'

      - name: Run Arduino Lint
        run: arduino-cli lint .
            
